"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductList = exports.User = exports.Product = exports.Payment = exports.Address = void 0;
const Address_entitie_1 = require("./Address.entitie");
Object.defineProperty(exports, "Address", { enumerable: true, get: function () { return Address_entitie_1.Address; } });
const Payment_entitie_1 = require("./Payment.entitie");
Object.defineProperty(exports, "Payment", { enumerable: true, get: function () { return Payment_entitie_1.Payment; } });
const ProductList_entitie_1 = require("./ProductList.entitie");
Object.defineProperty(exports, "ProductList", { enumerable: true, get: function () { return ProductList_entitie_1.ProductList; } });
const Products_entitie_1 = require("./Products.entitie");
Object.defineProperty(exports, "Product", { enumerable: true, get: function () { return Products_entitie_1.Product; } });
const User_entitie_1 = require("./User.entitie");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_entitie_1.User; } });
