"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createProductService = exports.updateProductService = exports.getProductsService = exports.deleteProductService = void 0;
const deleteProducts_service_1 = require("./deleteProducts.service");
Object.defineProperty(exports, "deleteProductService", { enumerable: true, get: function () { return deleteProducts_service_1.deleteProductService; } });
const getProducts_service_1 = require("./getProducts.service");
Object.defineProperty(exports, "getProductsService", { enumerable: true, get: function () { return getProducts_service_1.getProductsService; } });
const pathProducts_service_1 = require("./pathProducts.service");
Object.defineProperty(exports, "updateProductService", { enumerable: true, get: function () { return pathProducts_service_1.updateProductService; } });
const products_service_1 = require("./products.service");
Object.defineProperty(exports, "createProductService", { enumerable: true, get: function () { return products_service_1.createProductService; } });
