"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteUserController = exports.listUsersController = exports.createUserController = exports.deleteProductController = exports.pathProductController = exports.getProductController = exports.createProductController = exports.createLoginController = void 0;
const loginController_1 = require("./loginController");
Object.defineProperty(exports, "createLoginController", { enumerable: true, get: function () { return loginController_1.createLoginController; } });
const products_Controller_1 = require("./products.Controller");
Object.defineProperty(exports, "createProductController", { enumerable: true, get: function () { return products_Controller_1.createProductController; } });
Object.defineProperty(exports, "getProductController", { enumerable: true, get: function () { return products_Controller_1.getProductController; } });
Object.defineProperty(exports, "pathProductController", { enumerable: true, get: function () { return products_Controller_1.pathProductController; } });
Object.defineProperty(exports, "deleteProductController", { enumerable: true, get: function () { return products_Controller_1.deleteProductController; } });
const users_Controller_1 = require("./users.Controller");
Object.defineProperty(exports, "createUserController", { enumerable: true, get: function () { return users_Controller_1.createUserController; } });
Object.defineProperty(exports, "listUsersController", { enumerable: true, get: function () { return users_Controller_1.listUsersController; } });
Object.defineProperty(exports, "deleteUserController", { enumerable: true, get: function () { return users_Controller_1.deleteUserController; } });
